### ISSUE TITLE
Как я сосал у слона

### ISSUE THREAD

**Issue by obiebozza** [lineage2thread/lineage2#1]
Мы с корешем срали под дверь запасную сзади цирка, в восьмом классе это было, съебались из школы и курили возле цирка, потом кореш мне говорит: давай под двери насрем! давай, ты первый. Я говорю, ну ладно. Мы и до этого клоунов доебывали постоянно, делали всякие пакости, били стекла в цирке камнями, писали на стенах "клоуны пидарасы" и съебывались потом, сторожа нас ловить заебались, но ни разу не поймали, цирк рядом был от нас недалеко. Ну вот, я короче штаны снял и насрал на ступеньки под дверью кучу большую, я еще жопу чуть приморозил, зима была. Тут из этой двери выходит клоун с красным носом и в длинных ботинках, он еще в говно мое наступил. Кореш съебался, а меня клоун поймал, я в штанах своих запутался и ебнулся.

Короче завел он меня через эту дверь, а там воняет как в сарае ссаниной, говном и псиной какой-то, и темно, хуево видно блядь. Ну клоун мне пизды дал слегка, а потом развязывает тесемки своих штанов, они у него до самой шеи были и штанины разные, и говорит мне: ну все блядь, ты щас у меня сосать будешь, пидор! Ну я стал плакать, просил: дяденька клоун, только в рот не ебите! Клоун тогда говорит: ну тогда ты пидор будешь говно слона жрать! И завел меня в загон к слону, там были клетки со зверями, поэтому так мочой несло. Ну я с земли говно слона поднимал и ел его, здоровые такие катяхи. Мне на вкус показалось хуево, я обрыгался блядь, слону на ногу нарыгал. Клоун меня стал хуярить своими разноцветными ботинками, грит: ах ты блядь, ты нахуя слона обрыгал сука? теперь проси прощения у слона, грит соси у него хуй, а то я тебе в жопу хобот засуну! Я говорю: блядь, как я буду у слона сосать, его хуй мне в рот не вместится! Клоун мне прохуярил, я стал плакать, встал на колени, залез под слона и стал лизать ему залупу и яйца, они у него как мячи баскетные, только в кожаных таких мешочках. И дырку сосал у слона в хуе, чмакал и языком в ней вертел туда-сюда, я хорошо старался, чтобы клоун мне пизды не дал. Дырка в залупе у слона прям как пизда, такая же большая, руку можно засунуть полностью. Когда я сосал у слона дырку, он чото ворчал и переступал с ноги на ногу, видать ему нравилось, а дырка была соленая и мочой пиздец воняла. Клоун стоял рядом и смотрел, чтобы я хорошо сосал. Потом он мне уебал за то что грит "хули ты так хуево сосешь, что слон никак кончить не может? " и заставил меня дрочить слону шкуру на шишке, и у слона молофья как польется, и мне на голову и на куртку, у меня аж шапка к волосам прилипла намертво, я весь в молофье был, и еще он на спину мне насрал, когда кончил, от удовольствия наверно. Потом клоун меня хотел заставить говно убирать на ступеньках, которое я насрал, но я вырвался и съебался от него, когда съебывался я, то заметил, что в клетке напротив сидела здоровая такая обезьяна с высунутым красным хуем, она все это время смотрела, как я у слона сосал, и какую-то хуйню базарила, прыгала и делала так: у у у. Снегом потерся-потерся, весь слипся от слоновой молофьи. Корешу я ничего не стал говорить, сказал что клоун мне просто пизды дал, мамке соврал, что я в колодец провалился и оттого весь мокрый. К цирку с тех пор мы больше не ходили.

**Comment by lineage2thread** [comment]
Cool story, bro.
