### ISSUE TITLE
Вы че ебанулись как в это играть без бота?

### ISSUE THREAD

**Issue by obiebozza** [lineage2thread/lineage2#2]
Вы че ебанулись как в это играть без бота? Волкер какой нибудь работает? Нейросетку пробовал кто прикрутить?

**Comment by lineage2thread** [comment]
> Вы че ебанулись как в это играть без бота? Волкер какой нибудь работает? Нейросетку пробовал кто прикрутить?

Боты палятся, волкер не работает, нейросетку можешь пробнуть прикрутить, но, скорее всего тебя, набутылят, там не дураки сидят.
А вообще пиши в тред, зачем сюда писать.
